Repository voxel51/eta, pull requests merged in 2018-07, with the labels that each got.

#93 C3D featurizer
  eta/core/c3d.py
  eta/core/serial.py
  eta/core/tfutils.py
  eta/core/vgg16.py
  eta/core/video.py
  eta/models/manifest.json
Labels: feature

#102 Making confidence an optional parameter for detected objects
  eta/core/objects.py
Labels: enhancement

#103 Adding ability to compute intersections of bounding boxes and related quantities
  eta/core/geometry.py
Labels: feature

#107 Add `index_in_frame` to DetectedObject
  eta/core/objects.py
Labels: enhancement

#108 Adding method to VideoStreamInfo to get the aspect ratio of a video
  eta/core/video.py
Labels: feature

#110 Call Serializable attributes
  eta/core/data.py
Labels: bug

#112 Container tweaks
  eta/core/serial.py
Labels: enhancement

#115 when we switched the Container _validate method to an instance method…
  eta/core/config.py
  eta/core/serial.py
Labels: bug, hotfix

#120 Making the new DataFileSequence handle both immutable and mutable
  eta/core/data.py
  eta/core/utils.py
Labels: enhancement
