Repository voxel51/eta, pull requests merged in 2018-08, with the labels that each got.

#132 Tweak data.py
  eta/core/data.py
  eta/core/serial.py
Labels: enhancement

#139 Fixing __elements__ bug in DataRecords
  eta/core/data.py
Labels: bug

#140 Adding a command-line flag to refresh all module metadata files
  eta/core/command.py
  eta/core/metadata.py
Labels: feature

#142 `eta.core.frames` module to support per-frame labels (+ more)
  eta/core/config.py
  eta/core/features.py
  eta/core/frames.py
  eta/core/types.py
  eta/core/video.py
Labels: feature

#144 Fix bugs in `eta.core.utils`
  eta/core/utils.py
Labels: bug

#145 Merging FFmpegVideoResizer and FFmpegVideoSampler into FFmpeg
  docs/pipelines_dev_guide.md
  eta/core/command.py
  eta/core/video.py
  eta/modules/format_videos.json
  eta/modules/format_videos.py
  eta/modules/sample_videos.json
  eta/modules/sample_videos.py
  eta/pipelines/video_clipper.json
  eta/pipelines/video_formatter.json
  examples/demo_video/clip_videos.json
  examples/demo_video/format_videos.json
  examples/demo_video/pipeline.json
  examples/demo_video/resize_videos.json
  examples/demo_video/sample_videos.json
  examples/demo_video_clipper/request.json
  examples/demo_video_formatter/request.json
Labels: bug, enhancement

#146 Full support for publishing pipeline outputs
  eta/core/builder.py
  eta/core/data.py
  eta/core/pipeline.py
  eta/core/types.py
  eta/core/utils.py
Labels: feature

#147 Adding support for optional weights in `eta.core.numutils.Accumulator`
  eta/core/models.py
  eta/core/numutils.py
Labels: feature

#149 Adding a --debug flag to `eta build`
  eta/core/command.py
  eta/core/utils.py
Labels: feature

#150 Support for customizing tf.Config in the ETA config and customizing the ETA config when building/running pipelines
  eta/__init__.py
  eta/core/builder.py
  eta/core/c3d.py
  eta/core/command.py
  eta/core/config.py
  eta/core/job.py
  eta/core/module.py
  eta/core/pipeline.py
  eta/core/tfutils.py
  eta/core/utils.py
  eta/core/vgg16.py
  eta/core/video.py
Labels: feature

#151 Renaming eta build --config to --eta-config
  eta/core/command.py
Labels: enhancement

#152 Fixing return bug in eta.core.tfutils.make_tf_session
  eta/core/tfutils.py
Labels: bug

#154 Adding an `eta.core.tfutils.make_tf_config` method to build a custom `tf.ConfigProto`
  eta/core/tfutils.py
Labels: enhancement

#155 Adding various flags to eta command-line tool for building, running, and cleaning-up pipelines
  config-example.json
  eta/core/builder.py
  eta/core/command.py
  eta/core/pipeline.py
Labels: feature

#156 Pipeline optimization during building
  eta/core/builder.py
  eta/core/command.py
  eta/core/pipeline.py
  eta/core/serial.py
  eta/core/utils.py
  eta/core/video.py
  eta/core/ziputils.py
Labels: feature

#160 Adding remote storage module and documentation to ETA
  docs/storage_dev_guide.md
  eta/core/storage.py
  requirements.txt
Labels: feature

#163 Adding a standardize_strs method to cast all strings via str()
  eta/core/utils.py
Labels: enhancement
