Repository voxel51/eta, pull requests merged in 2019-09, with the labels that each got.

#294 Make image/video format checks case-insensitive
  eta/core/image.py
  eta/core/video.py
Labels: bug

#295 Fixes issue #288
  eta/core/datasets.py
Labels: bug

#293 Adding support for uploading/downloading directories to GCS
  eta/core/storage.py
  eta/core/utils.py
Labels: feature

#306 Fixed bug in schema validation method
  eta/core/image.py
Labels: bug

#309 Specify directory in which to put TempDir
  eta/core/datasets.py
  eta/core/utils.py
Labels: enhancement

#311 `LabeledDataset` method to remove files
  eta/core/datasets.py
Labels: enhancement

#310 More de-duplication functions
  eta/core/utils.py
Labels: enhancement
