Repository voxel51/eta, pull requests merged in 2019-12, with the labels that each got.

#352 Adding support for using StorageClients from the ETA CLI
  eta/__init__.py
  eta/constants.py
  eta/core/cli.py
  eta/core/serial.py
  eta/core/storage.py
  eta/core/types.py
  eta/core/utils.py
  eta/core/web.py
  requirements.txt
Labels: feature

#340 File method options for dataset copies, merges, adding files, and builders. And more!
  eta/core/datasets.py
  eta/core/utils.py
Labels: feature

#357 Fixes continuation token bug in S3StorageClient
  eta/core/storage.py
Labels: bug

#354 Adding support for using session tokens with S3StorageClient
  docs/storage_dev_guide.md
  eta/core/cli.py
  eta/core/storage.py
Labels: feature

#358 Adding functionality for balancing by object label
  eta/core/datasets.py
Labels: enhancement

#363 Python 2 compatibility fix
  eta/core/datasets.py
Labels: bug

#360 Adding pointers to docs and examples
  README.md
  examples/README.md
Labels: documentation, enhancement

#362 Adding support for searching/getting info for models/modules/pipelines via the ETA CLI
  eta/core/cli.py
  eta/core/module.py
  eta/core/pipeline.py
Labels: feature

#361 Adding support for extracting features from classifiers and detectors
  docs/export_tf_graphs_guide.md
  docs/visualize_tf_graphs_guide.md
  eta/classifiers/__init__.py
  eta/classifiers/tfslim_classifiers.py
  eta/core/features.py
  eta/core/learning.py
  eta/core/serial.py
  eta/core/tfutils.py
  eta/core/vgg16.py
  eta/detectors/__init__.py
  eta/detectors/tfmodels_detectors.py
  eta/detectors/tfmodels_segmenters.py
  eta/models/manifest.json
Labels: feature

#369 Classifier bugfix
  eta/classifiers/tfslim_classifiers.py
Labels: bug

#371 Adding CLI command for printing your ETA config
  eta/core/cli.py
Labels: enhancement

#368 Optionally include filepath when getting metadata about Google Drive files
  eta/core/cli.py
  eta/core/storage.py
Labels: feature

#370 Omitting GPU options from ETA config when GPU is not available on mac…
  eta/core/tfutils.py
Labels: enhancement

#372 Adding height/width/centroid to BoundingBox
  eta/core/geometry.py
Labels: enhancement

#374 Adding support for visualizing TF graph for a model
  eta/core/cli.py
Labels: feature

#367 Adding support for extracting features in classification/detection modules
  eta/classifiers/tfslim_classifiers.py
  eta/classifiers/vgg16_classifiers.py
  eta/core/features.py
  eta/core/learning.py
  eta/core/types.py
  eta/core/utils.py
  eta/core/vgg16.py
  eta/core/video.py
  eta/modules/apply_classifier_to_objects.json
  eta/modules/apply_classifier_to_objects.py
  eta/modules/apply_image_classifier.json
  eta/modules/apply_image_classifier.py
  eta/modules/apply_object_detector.json
  eta/modules/apply_object_detector.py
  eta/modules/embed_vgg16.py
  eta/pipelines/detect_and_classify_images.json
  eta/pipelines/image_classifier.json
  eta/pipelines/object_detector.json
  examples/README.md
  examples/demo_embed_vgg16/embed_image.py
  examples/demo_embed_vgg16/embed_image_direct.py
  examples/demo_embed_vgg16/embed_vgg16_module-config.json
  examples/demo_instance_segmentation/README.md
Labels: feature

#378 Optionally set Alpha = Confidence in AnnotationConfig
  eta/core/annotations.py
Labels: feature

#381 DetectedObject event indices (Proposal)
  eta/core/objects.py
Labels: enhancement
