Repository voxel51/eta, pull requests merged in 2019-07, with the labels that each got.

#245 Labeled Datasets
  eta/core/datasets.py
Labels: enhancement, feature

#246 Division by zero: frame_number_to_timestamp
  eta/core/video.py
Labels: bug

#262 Builder get_labels fix
  eta/core/datasets.py
Labels: bug

#257 Label filtering by schema
  eta/core/data.py
  eta/core/image.py
  eta/core/objects.py
  eta/core/serial.py
  eta/core/video.py
Labels: enhancement

#263 Adding copy for BuilderDataRecord
  eta/core/datasets.py
Labels: enhancement

#267 Empty labels functionality
  eta/core/datasets.py
Labels: enhancement

#265 Clipper backend
  eta/core/datasets.py
Labels: feature

#270 Clipper Transform needs some arg bounding
  eta/core/datasets.py
Labels: enhancement

#272 Extra Initialization Parameter for setting the Target Counts
  eta/core/datasets.py
Labels: enhancement

#269 Efficient/Reframed Balancer using numpy vector/matrix fun
  eta/core/datasets.py
Labels: enhancement

#276 Adding a Set class and using it in ImageSetLabels and VideoSetLabels
  eta/core/config.py
  eta/core/data.py
  eta/core/geometry.py
  eta/core/image.py
  eta/core/objects.py
  eta/core/serial.py
  eta/core/video.py
Labels: feature

#277 Fixed bug in `__iter__()` method of Set class
  eta/core/serial.py
Labels: bug

#278 BigContainer enhancements
  eta/__init__.py
  eta/core/annotations.py
  eta/core/serial.py
  eta/core/utils.py
  requirements.txt
Labels: enhancement

#275 BigContainer
  eta/__init__.py
  eta/core/annotations.py
  eta/core/geometry.py
  eta/core/serial.py
  eta/core/utils.py
  requirements.txt
Labels: enhancement, feature

#280 DataRecords Container fix
  eta/core/serial.py
Labels: bug
