Repository voxel51/eta, pull requests merged in 2019-08, with the labels that each got.

#283 LabeledDataset bug getting class
  eta/core/datasets.py
Labels: bug

#260 LabeledDatasetBuilder
  eta/core/datasets.py
Labels: feature

#290 Adding evaluation type to object labels
  eta/core/objects.py
Labels: feature

#291 ffmpeg fixes for strange video types
  eta/core/video.py
Labels: enhancement
