Repository voxel51/eta, pull requests merged in 2019-03, with the labels that each got.

#188 Adding a Markdown style guide
  docs/core_dev_guide.md
  docs/markdown_style_guide.md
  docs/modules_dev_guide.md
  docs/python_style_guide.md
Labels: documentation

#189 Adding interfaces for detectors and classifiers
  eta/core/learning.py
Labels: feature

#193 Data records fix
  eta/core/data.py
Labels: bug

#194 Only including top-level reflective attributes in Containers
  eta/core/data.py
  eta/core/serial.py
Labels: enhancement

#195 Storing image labels and video-level attributes
  eta/core/geometry.py
  eta/core/image.py
  eta/core/video.py
Labels: feature

#197 Adding VideoSetLabels class to encapsulate VideoLabels for a set of videos
  eta/core/data.py
  eta/core/image.py
  eta/core/types.py
  eta/core/video.py
Labels: feature

#200 Fixing handling of empty points arrays in GPSWaypoints
  eta/core/gps.py
Labels: bug, hotfix

#206 Adding docs for using the ImageLabels and VideoLabels classes
  docs/image_labels_guide.md
  docs/video_labels_guide.md
Labels: documentation

#209 added type for checkpoint files
  eta/core/types.py
Labels: feature

#207 Infrastructure for deploying classifiers
  eta/core/annotations.py
  eta/core/data.py
  eta/core/features.py
  eta/core/learning.py
  eta/core/numutils.py
  eta/core/objects.py
  eta/core/types.py
  eta/core/video.py
Labels: cleaning, documentation, feature
