Repository voxel51/eta, pull requests merged in 2019-11, with the labels that each got.

#331 TempDir: creating base directory if necessary
  eta/core/datasets.py
  eta/core/utils.py
Labels: enhancement

#332 S3 storage client
  docs/storage_dev_guide.md
  eta/core/storage.py
  requirements.txt
Labels: feature

#338 Only change `accel` to `min_accel` if `accel < min_accel`
  eta/modules/sample_videos.py
Labels: bug

#337 Handle `ffmpeg` errors in `sample_select_frames()`
  eta/core/video.py
Labels: bug

#344 Adding a max_unit field to human-readable methods to cap unit growth
  eta/core/utils.py
Labels: enhancement

#343 Consistent filenames after dataset transforms
  eta/core/datasets.py
Labels: enhancement

#342 Dataset wrangling helpers
  eta/core/datasets.py
  eta/core/image.py
  eta/core/video.py
Labels: enhancement

#345 Remove objects without attrs after filtering schema
  eta/core/datasets.py
  eta/core/image.py
  eta/core/objects.py
  eta/core/video.py
Labels: enhancement

#346 New `remove_objects_without_attrs` function
  eta/core/datasets.py
  eta/core/image.py
  eta/core/objects.py
  eta/core/video.py
Labels: enhancement

#347 Quickfix for incorrect logging of ffmpeg error
  eta/core/video.py
Labels: bug

#351 Improving docs
  docs/export_tf_graphs_guide.md
  docs/models_dev_guide.md
  eta/classifiers/tfslim_classifiers.py
Labels: documentation
