Repository voxel51/eta, pull requests merged in 2019-04, with the labels that each got.

#211 Adding support for rendering frame level attributes in ETA
  eta/core/annotations.py
  eta/core/data.py
  eta/core/models.py
  eta/core/objects.py
  eta/core/serial.py
Labels: enhancement

#212 Moving annotation parameters to an AnnotationConfig
  eta/core/annotations.py
  eta/modules/visualize_labels.json
  eta/modules/visualize_labels.py
Labels: enhancement

#213 Fixing attribute order for ModelManager
  eta/core/models.py
Labels: enhancement

#216 Casting to string to avoid py2-py3 str-bytes issues
  eta/core/serial.py
  eta/core/video.py
Labels: enhancement

#217 Gracefully handling bytes when loading JSON
  eta/core/serial.py
  eta/core/video.py
Labels: enhancement

#218 Fixing falsey parameter bug when building pipelines
  eta/core/builder.py
Labels: bug, hotfix

#221 Safe uploading for large files
  eta/core/storage.py
Labels: bug
