Repository voxel51/eta, pull requests merged in 2020-03, with the labels that each got.

#440 Adding script to build Docker images with ETA installed
  .dockerignore
  Dockerfile
  README.md
  docs/docker_build_guide.md
Labels: feature

#442 Adding method to read video as in-memory array
  eta/core/video.py
Labels: feature

#445 Adding more logging to core video-input modules
  eta/core/utils.py
  eta/core/video.py
  eta/modules/format_videos.py
  eta/modules/sample_videos.py
Labels: feature

#447 Handling rotated videos properly when computing frame size
  eta/core/video.py
Labels: bug

#441 Finishing support for switching between framewise and spatiotemporal format in Labels
  eta/core/annotations.py
  eta/core/data.py
  eta/core/datasets/builders.py
  eta/core/datasets/labeled_datasets.py
  eta/core/datasets/transformers.py
  eta/core/datasets/utils.py
  eta/core/events.py
  eta/core/frames.py
  eta/core/geometry.py
  eta/core/image.py
  eta/core/labels.py
  eta/core/objects.py
  eta/core/serial.py
  eta/core/types.py
  eta/core/video.py
Labels: feature

#448 Extract clip frames from video
  eta/core/frameutils.py
  eta/core/video.py
Labels: feature

#450 Read images from urls
  eta/core/image.py
  eta/core/web.py
Labels: enhancement, feature

#452 Turning off JSON pretty-printing by default when serializing
  eta/core/datasets/builders.py
  eta/core/serial.py
Labels: enhancement

#455 Module Metadata Bugfix
  eta/core/metadata.py
  eta/modules/apply_classifier_to_objects.json
  eta/modules/apply_classifier_to_objects.py
Labels: bug

#456 Adding support for default values to AttributeSchema
  eta/core/data.py
Labels: feature

#457 Adding support for visualizing TF checkpoints and exporting them as a frozen graphs
  docs/export_tf_graphs_guide.md
  docs/visualize_tf_graphs_guide.md
  eta/classifiers/tfslim_classifiers.py
  eta/core/image.py
  eta/core/tfutils.py
  eta/segmenters/tf_segmenters.py
Labels: feature

#458 Adding support for building BoundingBoxes and RelativePoints from absolute coordinates
  eta/core/geometry.py
  eta/detectors/tfmodels_detectors.py
Labels: feature
