Repository voxel51/eta, pull requests merged in 2020-01, with the labels that each got.

#382 Adding two useful help-related features to the CLI
  eta/core/cli.py
Labels: enhancement

#383 Passing VideoReader to video models
  eta/core/learning.py
  eta/modules/apply_video_classifier.json
  eta/modules/apply_video_classifier.py
  eta/modules/apply_video_model.json
  eta/modules/apply_video_model.py
Labels: feature

#384 Adding support for reseting VideoReaders
  eta/core/video.py
Labels: feature

#380 Adding support for exposing class probabilities for predictions/detections
  eta/classifiers/tfslim_classifiers.py
  eta/classifiers/vgg16_classifiers.py
  eta/classifiers/voting_classifiers.py
  eta/core/data.py
  eta/core/features.py
  eta/core/learning.py
  eta/core/objects.py
  eta/core/vgg16.py
  eta/detectors/tfmodels_detectors.py
  eta/models/manifest.json
  eta/modules/apply_classifier_to_objects.json
  eta/modules/apply_classifier_to_objects.py
  eta/modules/apply_image_classifier.json
  eta/modules/apply_image_classifier.py
  eta/modules/apply_object_detector.json
  eta/modules/apply_object_detector.py
  eta/pipelines/detect_and_classify_images.json
  eta/pipelines/image_classifier.json
  eta/pipelines/object_detector.json
  examples/demo_image_classifier/classify-images-tfslim-template.json
  examples/demo_image_classifier/classify-images-vgg16.json
  examples/demo_object_detector/detect-people.json
  examples/demo_object_detector/detect-vehicles.json
Labels: feature

#388 Falling back to GoogleDriveStorageClient when downloading models, if possible
  eta/core/models.py
Labels: bug

#391 Adding CLI guide, and support for autocomplete!
  README.md
  docs/cli_guide.md
  eta/core/cli.py
  requirements.txt
Labels: documentation, feature

#392 Bounding Box corner functionality
  eta/core/geometry.py
Labels: enhancement

#386 `LabeledDataset.data_dir` -> `LabeledDataset.dataset_dir`
  eta/core/datasets.py
  pylintrc
Labels: cleaning

#389 Apply Classifier to `LabeledImageDataset`
  eta/modules/apply_image_classifier.json
  eta/modules/apply_image_classifier.py
Labels: enhancement

#390 Making FrameRange and FrameRanges Serializable
  eta/core/datasets.py
  eta/core/video.py
Labels: feature

#395 adding LabeledFileRecord to ETA
  eta/core/data.py
Labels: enhancement

#397 Adding method to compute the overlap of two BoundingBoxes
  eta/core/geometry.py
Labels: feature

#398 Tweaking implementation of reindexing objects
  eta/core/video.py
Labels: enhancement

#399 Attribute Container accessor helpers
  eta/core/data.py
Labels: enhancement

#402 Fix dataset splits
  eta/core/datasets.py
Labels: bug

#403 Removes dependency of `setup.py` on `eta` package
  MANIFEST.in
  eta/__init__.py
  eta/constants.py
  eta/core/cli.py
  eta/version.json
  requirements.txt
  setup.py
Labels: enhancement

#406 Version for startup message
  eta/__init__.py
Labels: bug

#405 Image/VideoSetLabels from glob pattern
  eta/core/image.py
  eta/core/serial.py
  eta/core/video.py
Labels: enhancement

#407 Using version from `eta.constants`
  eta/__init__.py
Labels: enhancement

#408 Enhancements to annotation rendering via ETA
  eta/core/annotations.py
Labels: feature

#409 Scaling of annotations relative to media size (pixels)
  eta/core/annotations.py
Labels: feature

#412 Break them up! `eta.core.datsets` refactor
  eta/core/datasets.py
  eta/core/datasets/__init__.py
  eta/core/datasets/builders.py
  eta/core/datasets/labeled_datasets.py
  eta/core/datasets/split_methods.py
  eta/core/datasets/transformers.py
  eta/core/datasets/utils.py
  eta/core/datasets/video2image.py
Labels: cleaning

#415 Adding support for getting the active schema of LabeledDatasets
  eta/core/datasets/labeled_datasets.py
Labels: feature

#416 Small enhancements to modules/pipelines
  eta/core/builder.py
  eta/core/module.py
  eta/core/pipeline.py
  eta/core/utils.py
Labels: feature
